// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNpB3IraL7jT49kZiKU06QiX1u8YMgoX0',
    appId: '1:127435021638:web:4509c3037fd8916dcf1947',
    messagingSenderId: '127435021638',
    projectId: 'cinnex',
    authDomain: 'cinnex.firebaseapp.com',
    storageBucket: 'cinnex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg1h3GAoJsqBzV8o5mJZsQCAkZsTf05Jg',
    appId: '1:127435021638:android:15e3ebd95a538f9ccf1947',
    messagingSenderId: '127435021638',
    projectId: 'cinnex',
    storageBucket: 'cinnex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgTtyZ2KUv2OVtisw_sQIap0ATo4yTgU',
    appId: '1:127435021638:ios:b5f20d412e2b9506cf1947',
    messagingSenderId: '127435021638',
    projectId: 'cinnex',
    storageBucket: 'cinnex.firebasestorage.app',
    iosBundleId: 'com.example.cinnexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgTtyZ2KUv2OVtisw_sQIap0ATo4yTgU',
    appId: '1:127435021638:ios:b5f20d412e2b9506cf1947',
    messagingSenderId: '127435021638',
    projectId: 'cinnex',
    storageBucket: 'cinnex.firebasestorage.app',
    iosBundleId: 'com.example.cinnexMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNpB3IraL7jT49kZiKU06QiX1u8YMgoX0',
    appId: '1:127435021638:web:4fe94778bb980178cf1947',
    messagingSenderId: '127435021638',
    projectId: 'cinnex',
    authDomain: 'cinnex.firebaseapp.com',
    storageBucket: 'cinnex.firebasestorage.app',
  );

}